// <auto-generated />
using DestinyBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DestinyBot.Data.Migrations
{
    [DbContext(typeof(DestinyBotContext))]
    [Migration("20181213023754_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DestinyBot.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("EndTime");

                    b.Property<string>("Name");

                    b.Property<long>("StartTime");

                    b.Property<long>("TwitchStreamerId");

                    b.HasKey("Id");

                    b.HasIndex("TwitchStreamerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.GuildOwner", b =>
                {
                    b.Property<string>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelHub");

                    b.Property<string>("Snowflake");

                    b.Property<long>("TwitchId");

                    b.Property<long>("TwitterId");

                    b.Property<string>("YoutubeId");

                    b.HasKey("GuildId");

                    b.ToTable("GuildOwners");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.TwitchStreamer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long>("SteamStartTime");

                    b.Property<long>("StreamEndTime");

                    b.HasKey("Id");

                    b.ToTable("TwitchStreamers");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.TwitchSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlternateLink");

                    b.Property<string>("DiscordChannelId");

                    b.Property<long>("MessageId");

                    b.Property<bool>("ShouldPin");

                    b.Property<long>("TwitchStreamerId");

                    b.HasKey("Id");

                    b.HasIndex("TwitchStreamerId");

                    b.ToTable("TwitchSubscriptions");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.Youtube", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("LatestVideoDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.YoutubeSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiscordChannelId");

                    b.Property<string>("YoutubeId");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeId");

                    b.ToTable("YoutubeSubscriptions");
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.Game", b =>
                {
                    b.HasOne("DestinyBot.Data.Entities.TwitchStreamer", "TwitchStreamer")
                        .WithMany("Games")
                        .HasForeignKey("TwitchStreamerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.TwitchSubscription", b =>
                {
                    b.HasOne("DestinyBot.Data.Entities.TwitchStreamer", "TwitchStreamer")
                        .WithMany("TwitchSubscriptions")
                        .HasForeignKey("TwitchStreamerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DestinyBot.Data.Entities.YoutubeSubscription", b =>
                {
                    b.HasOne("DestinyBot.Data.Entities.Youtube", "Youtube")
                        .WithMany("YoutubeSubscriptions")
                        .HasForeignKey("YoutubeId");
                });
#pragma warning restore 612, 618
        }
    }
}
